import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./index.css";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";
import { getCategoryArticleCounts } from "@/libs/microcms";
import Providers from "./providers";
// TODO metaタグの設定
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const categories = await getCategoryArticleCounts();

  return (
    <html lang="ja">
      <head></head>
      <body>
        <Providers>
          <Header categories={categories} />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
